### ISSUE TITLE
Déployer sur shinyapps.io ?

### ISSUE THREAD

**Issue by phileas-condemine** [deepPhong/thot#2]
S'il n'y a pas de problème de confidentialité des données nous pouvons vous proposer de partager notre compte shinyapps.io de la DREES (actuellement compte pro avec 10k heures/mois) http://dataviz.drees.solidarites-sante.gouv.fr/ afin que les utilisateurs n'aient pas besoin de cloner le repo, gérer les packages, la version de R et de lancer l'appli en local.

**Comment by deepPhong** [comment]
Ce serait chouette, mais malheureusement les données à importer dans l'application sont pour le moment nominatives (extractions de la base SIMPA de l'AP-HP) et ne peuvent donc pas être hébergées temporairement à l'extérieur des serveurs de l'AP-HP. Merci d'avoir proposé !
